### FONTS ###
font_family      family="ProFont IIx Nerd Font Mono"
font_size	12

### SHELL ###
shell 		zsh
confirm_os_window_close	0

### LOOKS ###
window_padding_width	20 	

### THEME ###
include current-theme.conf

### SCROLLBAR ###
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0
scrollbar_handle_opacity 0
