##############
### SOURCE ###
##############

source = ~/.config/hypr/configs/general.conf
source = ~/.config/hypr/configs/deco.conf
source = ~/.config/hypr/configs/binds.conf
source = ~/.config/hypr/configs/animation.conf

