###############
### GENERAL ###
###############

general {
    gaps_in = 5
    gaps_out = 55,20,20,55

    border_size = 2

    col.active_border = rgb(129,161,193)
    col.inactive_border = rgb(76,86,106)

    resize_on_border = false

    allow_tearing = false

    layout = dwindle
}

input {
    kb_layout = us, cz
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    numlock_by_default = true
    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}

### MONITOR ###
monitor=,preferred,auto,auto

### CURSOR ###
env = XCURSOR_THEME,Bibata-Modern-Classic
env = XCURSOR_SIZE,24

env = HYPRCURSOR_THEME,Bibata-Modern-Classic
env = HYPRCURSOR_SIZE,24

### MISC ###
dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = -1 
    disable_hyprland_logo = false 
}

gesture = 3, horizontal, workspace

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

###################
### WINDOW RULE ###
###################

### MAIN ###
windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

### WIFI ###
windowrulev2 = float, class:^(com.network.manager)$
windowrulev2 = size 500 800, class:^(com.network.manager)$
windowrulev2 = move 1400 50, class:^(com.network.manager)$

### PAVUCONTROL ###
windowrulev2 = float, class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = size 500 800, class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = move 1400 50, class:^(org.pulseaudio.pavucontrol)$

